server:
  port: 8900
logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3600
    jedis:
      pool:
        max-active: 10
        max-idle: 3
        min-idle: 3
quartz:
  enabled: true
