server:
  port: 6001
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    contextPath:

spring:
  application:
    name: ofs-sys
  profiles:
    #  从外部项目引入 include ,从本目录引用active
    include: @env@
    # active: @env@
  level:
    root: debug
  aop:
    proxy-target-class: true
    auto: true
ofs:
  config:
    encryptEnable: false
  quartz:
    enable: false
  auth:
    password-retry-limit: 5
    kickOutValid: false
    ignoreUrl:
    - /swagger-resources/**
    - /webjars/**
    - /v2/api-docs/**
