server:
  port: 6001
  servlet:
    contextPath: /api

dubbo:
  protocol:
    name: dubbo
    port: 29300
    payload: 83886080
  scan:
    base-packages: com.ryx.tax.merchant
  consumer:
    check: false
spring:
  application:
    name: csm-metchant-service
  profiles:
    include: @env@

  level:
    root: debug
mybatis:
  type-aliases-package: com.ryx.tax.merchant.model
  mapper-locations: classpath:mapper/*.xml

