server:
  port: 6001
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    contextPath:

spring:
  application:
    name: ofs-sys
  profiles:
    active: @env@
  level:
    root: debug
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3600
    jedis:
      pool:
        max-active: 10
        max-idle: 3
        min-idle: 3
  aop:
    proxy-target-class: true
    auto: true
