spring:
  activemq:
    broker-url: failover:(tcp://12.3.10.184:61616,tcp://12.3.10.185:61616,tcp://12.3.10.186:61616)?randomize=false
    pool:
      enabled: true
      max-connections: 10
  redis:
    sentinel:
      nodes: 12.3.10.111:26380,12.3.10.111:26381
      master: account
    jedis:
      pool:
        max-active: 100
        max-wait: 15000
        min-idle: 10
    timeout: 30000
    password: ryx_settle_cach
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    url: jdbc:oracle:thin:@12.3.10.15:1521/qjsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ofs?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: ofs
    password: 123456
    druid:
      # 初始化时建立的连接数
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 50
      # 获取连接最大等待时间，单位：毫秒
      max-wait: 60000
      validation-query: select 1 from dual
      validation-query-timeout: 2
      #是否强制关闭连接时长大于removeAbandonedTimeoutMillis的连接
      remove-abandoned: true
      #一个连接从被连接到被关闭之间的最大生命周期
      remove-abandoned-timeout: 180
      #强制关闭连接时是否记录日志
      log-abandoned: true
      time-between-log-stats-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,config
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKixuSaOFuMGj3zQcJaxIxhhYUUmlVZ7wyFqedH61u8BDIt+sAjCHWFjL4mK/c7LGjovkuNzp+yuunvO1U+EFrUCAwEAAQ==
      filter:
        config:
          enabled: true
        stat:
          log-slow-sql: true
        wall:
          config:
            multi-statement-allow: false
dubbo:
  metadata-report:
    address: zookeeper://12.3.10.184:2182?backup=12.3.10.185:2182,12.3.10.186:2182
  registry:
    address: zookeeper://12.3.10.184:2182?backup=12.3.10.185:2182,12.3.10.186:2182
  consumer:
    check: false
  timeout: 30000
