logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ofs?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3600
    jedis:
      pool:
        max-active: 10
        max-idle: 3
        min-idle: 3
  aop:
    proxy-target-class: true
    auto: true

ofs:
  config:
    encryptEnable: false
  quartz:
    enable: false
  auth:
    password-retry-limit: 5
    kickOutValid: false
